version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

  api:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://myuser:mypassword@db:3306/mydatabase
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs/api:/app/logs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data: 