version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/project/app
    depends_on:
      - redis
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    volumes:
      - ./app:/project/app
    depends_on:
      - redis
    env_file:
      - .env
    command: celery -A app.celery_worker.celery worker --loglevel=info

  beat:
    build: .
    volumes:
      - ./app:/project/app
    depends_on:
      - redis
    env_file:
      - .env
    command: celery -A app.celery_worker.celery beat --loglevel=info -s /tmp/celerybeat-schedule 